"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random 
position.
Find the letter that was added in t.

Example:
	Input:
	s = "abcd"
	t = "abcde"
	Output:
	e
	Explanation:
	'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        sum_s = 0
        sum_t = 0
        for i in s:
            sum_s += ord(i)
        for j in t:
            sum_t += ord(j)
        return chr(sum_t - sum_s)